/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package game;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
/**
 *
 * @author Usuario
 */
public class juego extends JFrame {
    private JLabel lblImagen;
    private JLabel lblErrores;
    private JPanel panelLetras;
    private JLabel lblAdivinar;
    private GameFacade gameFacade;

    public juego() {
        gameFacade = new GameFacade();
        initUI();
        initGame();
    }

    private void initUI() {
        setTitle("Juego de Ahorcado");
        setSize(600, 400);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        setLayout(new BorderLayout());

        // Panel superior con la imagen del ahorcado
        lblImagen = new JLabel();
        lblImagen.setHorizontalAlignment(SwingConstants.CENTER);
        add(lblImagen, BorderLayout.NORTH);

        // Panel central con la palabra a adivinar
        lblAdivinar = new JLabel();
        lblAdivinar.setFont(new Font("Arial", Font.PLAIN, 24));
        lblAdivinar.setHorizontalAlignment(SwingConstants.CENTER);
        add(lblAdivinar, BorderLayout.CENTER);

        // Panel inferior con las letras y errores
        JPanel panelInferior = new JPanel(new BorderLayout());
        
        // Panel de errores
        lblErrores = new JLabel("Errores: 0");
        lblErrores.setHorizontalAlignment(SwingConstants.CENTER);
        panelInferior.add(lblErrores, BorderLayout.NORTH);

        // Panel de letras
        panelLetras = new JPanel(new GridLayout(3, 9));
        for (char c = 'A'; c <= 'Z'; c++) {
            JButton btnLetra = new JButton(String.valueOf(c));
            btnLetra.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    gameFacade.procesarLetra(c);
                    actualizarUI();
                    
                }

            });
            panelLetras.add(btnLetra);
        }
        panelInferior.add(panelLetras, BorderLayout.CENTER);

        add(panelInferior, BorderLayout.SOUTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 559, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new juego().setVisible(true);
            }
        });
    }

    private void initGame() {
               gameFacade.iniciarJuego();
        actualizarUI();
    }

            private void actualizarUI() {
                         lblImagen.setIcon(new ImageIcon(gameFacade.obtenerImagen()));
                            lblAdivinar.setText(gameFacade.obtenerPalabraAdivinada());
                            lblErrores.setText("Errores: " + gameFacade.obtenerErrores());}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
